version: '3.8'

services:
  api:
    build: .
    container_name: medicine_inventory_api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=medicine_inventory
      - JWT_SECRET_KEY=medicine-inventory-super-secret-jwt-key-for-portfolio
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: medicine_inventory_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
